name: "C-Vision"

url: "http://kolkir.github.io"

paginate: 3
permalink: pretty

social:
    GitHub: "https://github.com/Kolkir"
    LinkedIn: "http://ua.linkedin.com/pub/kirill-kolodyazhniy/14/969/79b"
    Google: "https://www.google.com/+KirillKolodyazhniy"
